### PR TITLE
Add dart to language-detector

### PR DESCRIPTION
**Pull request by szczerski**

### CODE REVIEW

**Comment by pomber** [comment]
Hey @szczerski, why did you close it? Does it work"

**Comment by szczerski** [comment]
Hi, I'm just learning how github works. Git-history looks and works great, however, I noticed that the dart language is missing, and now more and more will be written using flutter. That's why I added the same code as for other languages. However, something went wrong.
Sorry for the mess.

**Comment by pomber** [comment]
@szczerski  I can't reopen it because I think you deleted the fork. Wanna try again in a new PR? I can help you if you need.

**Comment by szczerski** [comment]
My commit would have passed before the test-prettier was added.
The problem appears after the commit 'Add prettier' 941a28ad39703.

**Comment by pomber** [comment]
That should be easy to fix, you need to run `yarn format` and commit the changes. You can also install prettier in your code editor, it's an amazing tool

**Comment by szczerski** [comment]
Thanks for the hints @pomber . I changed the prettier path to
`\"src/**/*.{js,jsx,md,json,html,css,yml}\"` or without the quotes `*.{js,jsx,md,json,html,css,yml}` and pass the tests. I am now on Windows, maybe tomorrow I'll check if Linux will pass tests without changing the path.

**Comment by szczerski** [comment]
This time, it passes (PR #82) and linux has no problems with the path.

**Pull request closed without merging**
